### ISSUE TITLE
Switching between Nightly builds and releases

### ISSUE THREAD

**Issue by frodeseverin** [cgeo/cgeo-fdroid#1]
# Testing bug fix

I just tested a feature in NB-2016-09-04, and wanted to go back to release 2016-08-27 for production use.

Here is a recap of what I did:
- Downloaded standard version from Google Play
  - Used this for a while, and decided to go for the beta vesrion
- Downloaded beta version from Google Play after signing up for beta
- Reported bug about GeoKret search
- Added F-Droid repositories for release and nigtlies
- Downloaded NB-2016-09-04
  - To test patch
- Tested patch in NB-2016-09-04
  - Patch verified OK
- Tried to roll back to release 2016-08-27 from F-Droid manager
- Encountered 'Unknown Error' in F-Droid manager
- Uninstalled c:geo from F-Droid manager
- Installed release 2016-08-27 from F-Droid manager
# 
# Expected result

All or most settings and data should survive the rollback
# Actual result

Seemingly most settings survived.
Notably the lists of saved caches disappeared.
# 
# What to do next?

How can I restore theese lists?
Reentering them manually is a lot of tedious work.

**Comment by samueltardieu** [comment]
In settings / system, you can backup your database and restore it. The "unknown error" you've encountered is probably due to a refusal to downgrade from Android.

**Comment by SammysHP** [comment]
Also due to changes of the database schema it might not be possible to downgrade from nightly/RC to release.

**Comment by kumy** [comment]
@SammysHP I stayed at a point where (now) our current release _is_ backward compatible with NB

**Comment by samueltardieu** [comment]
> Also due to changes of the database schema it might not be possible to downgrade from nightly/RC to release.

Right, although this should not be the case in the above mentioned versions.

**Comment by SammysHP** [comment]
Yes, at the moment. But it is not the case in general. Our code in [cgeo.geocaching.storage.DataStore#onUpgrade()](https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/storage/DataStore.java#L570) does not handle downgrades. If you do not know whether the schema has changed it is risky to downgrade (also from release to older release).

**Comment by frodeseverin** [comment]
So my database is lost, then?
Or can I restore it manually from some sql database?

A small note giving this heads up for nightly testers on http://www.cgeo.org/development.html would be appreciated.

**Comment by SammysHP** [comment]
I thought it was there. @Lineflyer

**Comment by frodeseverin** [comment]
The only mention of database backup I have found so far is here:
http://www.cgeo.org/faq.html#replace-device
And under 'Settings => System => Backup' in the app itself.

I suppose I ran into the caveat this time.

**Comment by Lineflyer** [comment]
I will add some note of this downgrade limitation to our web page. Opening a new issue in a matching repo for that.
