### ISSUE TITLE
fdroid.cgeo.org not found

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo-fdroid#10]
Looks like the DNS entry for fdroid.cgeo.org is missing.

**Comment by john-magnus** [comment]
![Screenshot_20230923-093453](https://github.com/cgeo/cgeo-fdroid/assets/1545102/72978f15-415f-4cd0-a6e8-db87ff95b87d)
I'm not that versed in fdroid, so I'm not aware of any method to get logs or extended error information. So the most info I can figure out is what's visible in the toast message returned by fdroid.

**Comment by SammysHP** [comment]
@kumy
fdroid.cgeo.org is a CNAME to cgeo.geokretymap.org, but whole geokretymap.org has no DNS records anymore.

**Comment by Lineflyer** [comment]
I chatted with @mucek4 today, he will change the CNAME record probably tomorrow.

**Comment by kumy** [comment]
Yes sorry for that. I did not renew geokretymap.org, as the feature is included in geokrety.org now. I forgot we such domain configuration. I requested by mail on Sept 19 to change the entry to cgeo.geokrety.org.

**Comment by john-magnus** [comment]
Confirmed withing again.

**Comment by Lineflyer** [comment]
Thanks for the feedback. Closing then.
