### ISSUE TITLE
Repo is not working with F-droid Basic 1.19.0-alpha0

### ISSUE THREAD

**Issue by realAllonZ** [cgeo/cgeo-fdroid#11]
I am no longer able to connect with the c:geo F-droid repo:

https://fdroid.cgeo.org/?fingerprint=370bb4d550c391d5dccb6c81fd82fda4892964764e085a09b7e075e9bad5ed98

Please say it ain't so!

**Comment by kumy** [comment]
I got an update this morning. It should be up. I'll double check tomorow.

**Comment by kumy** [comment]
- https://fdroid.cgeo.org/index.xml :heavy_check_mark: 
- https://fdroid.cgeo.org/cgeo-release-2023.10.25.apk :heavy_check_mark: 
- Checked the logs while refreshing repositories on my fdroid :heavy_check_mark: 

Seems working fine for me.

**Comment by realAllonZ** [comment]
I see that the repo is working correctly with F-droid. However, it is not working for me using F-droid basic. See the screenshots bellow for confirmation:

![Screenshot1_F-Droid Basic](https://github.com/cgeo/cgeo-fdroid/assets/34382225/41df3c94-e505-485a-9ef4-b2fa485eac7a)

![Screenshot2_F-Droid Basic](https://github.com/cgeo/cgeo-fdroid/assets/34382225/14150827-eda4-44b8-9493-c721a1bb3ce7)

**Comment by kumy** [comment]
I installed and tested fdeoid basic. It's also working here. But I don't have the same the same UI as you. What is your fdroid basic version ? I have 1.18.0

![Screenshot_20231030-073843.png](https://github.com/cgeo/cgeo-fdroid/assets/176794/f28ceff8-1085-4d11-af0c-3fac0240065c)

![Screenshot_20231030-073835.png](https://github.com/cgeo/cgeo-fdroid/assets/176794/d8afb19b-d2f6-4ea0-bd2e-88f828ac0497)

![Screenshot_20231030-073831.png](https://github.com/cgeo/cgeo-fdroid/assets/176794/48fe15a8-9a78-4590-9353-c857d7c54aff)

![Screenshot_20231030-073903.png](https://github.com/cgeo/cgeo-fdroid/assets/176794/b59be3dd-16f1-4732-87de-ae8fbea4d906)

![Screenshot_20231030-074142.png](https://github.com/cgeo/cgeo-fdroid/assets/176794/1c909e29-9cde-4e24-a168-637a3d65af93)

**Comment by realAllonZ** [comment]
I was on F-droid Basic 1.19.0-alpha0 and when I downgraded to 1.18.0 the repo was added successfully.

Thanks for helping me track down the issue @kumy

**Comment by realAllonZ** [comment]
I was about to post about this issue on [New Issue · F-Droid / Client · GitLab](https://gitlab.com/fdroid/fdroidclient/-/issues), but while gathering more screenshots I realized that your repo was the only one that was not working with Basic Alpha.

I also tried adding the repo on F-Droid 1.18.0 and F-Droid 1.19.0-alpha0, several times, with relatively similar results. Though the 1st time Alpha did recognized the repo and subsequent attempts on Alpha revealed the Invalid Repo org.fdroid.download.NotFoundException

With this new information, it is possible that the issue may be with the c:geo repo after all. 

I will wait for your response before posting the issue to F-Droid on GitLab.

**Comment by kumy** [comment]
I also think something needs to be updated on our side. Now that I know how to reproduce I will have a second look at the issue :)

**Comment by kumy** [comment]
I've pushed a new commit to the repo, updating the `nginx` config. @realAllonZ Please test again :pray: 

I've found that when adding the repository, `F-Droid Basic 1.19.0-alpha0` look for the index files in the folder `/fdroid/repo` instead of `/` as we used to. Once the repo is added, all  subsequent `HEAD`/`GET` are done to the old know urls.

Not sure if it's a bug or not :shrug: 

```
# Adding the repo for the first time. The indexes a searched in the `/fdroid/repo` instead of `/`
 xxx - - [30/Oct/2023:18:31:41 +0000] "GET /fdroid/repo/entry.jar HTTP/1.1" 404 153 "-" "F-Droid 1.19.0-alpha0"
 xxx - - [30/Oct/2023:18:31:41 +0000] "HEAD /fdroid/repo/index-v1.jar HTTP/1.1" 200 0 "-" "F-Droid 1.19.0-alpha0"
 xxx - - [30/Oct/2023:18:31:42 +0000] "GET /fdroid/repo/index-v1.jar HTTP/1.1" 200 5349 "-" "F-Droid 1.19.0-alpha0"

# just after adding, there is a confirmation step. Once validated, new requests are done on plain old known url
 xxx - - [30/Oct/2023:18:31:51 +0000] "HEAD /entry.jar HTTP/1.1" 404 0 "-" "F-Droid 1.19.0-alpha0"
 xxx - - [30/Oct/2023:18:31:51 +0000] "HEAD /index-v1.jar HTTP/1.1" 200 0 "-" "F-Droid 1.19.0-alpha0"
 xxx - - [30/Oct/2023:18:31:51 +0000] "GET /index-v1.jar HTTP/1.1" 200 5349 "-" "F-Droid 1.19.0-alpha0"

# Then subsequent enable/disable/reload of the repositories use the old known url
 xxx - - [30/Oct/2023:18:32:03 +0000] "HEAD /entry.jar HTTP/1.1" 404 0 "-" "F-Droid 1.19.0-alpha0"
 xxx - - [30/Oct/2023:18:32:03 +0000] "HEAD /index-v1.jar HTTP/1.1" 200 0 "-" "F-Droid 1.19.0-alpha0"
```

**Comment by realAllonZ** [comment]
The c:geo repo is now being recognized by F-droid Basic 1.19.0-alpha

Thanks @kumy 

Shall I post the possible bug to [New Issue · F-Droid / Client · GitLab ](https://gitlab.com/fdroid/fdroidclient/-/issues)?

**Comment by kumy** [comment]
> Shall I post the possible bug to New Issue · F-Droid / Client · GitLab ?

As you wish 🤷, but I would be interested to know if it's a feature or a bug...

**Comment by kumy** [comment]
https://gitlab.com/fdroid/fdroidserver/-/blob/master/examples/config.yml#L51-53
The issue seems to be our old version of the server.

**Comment by kumy** [comment]
Created #12 for the upgrade task
