### ISSUE TITLE
New ip for fdroid executor

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo-fdroid#3]
@mucek4 may you please change the allowed ip from 163.172.156.112 to 176.31.245.24 to connect on jenkins (fdroid-executor).

Thanks

**Comment by mucek4** [comment]
Done.

**Comment by kumy** [comment]
Thanks.
@Lineflyer I ve seen a failure,  I ll check this evening.

On May 23, 2017 7:31:50 AM GMT+02:00, mucek4 <notifications@github.com> wrote:
>Done.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo-fdroid/issues/3#issuecomment-303294597

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment]
Fixed.
