### ISSUE TITLE
fdroid nightly not accessible

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo-fdroid#6]
Trying to access the fdroid nightly repo (https://fdroid.cgeo.org/nightly/) in a browser yields an error 403.
Users report that no nightlies are announced in the fdroid app since about 5 days.

**Comment by kumy** [comment]
I have nightlies available on my phone:
* 2019.04.23-NB-fc3ae32
* 2019.04.23-NB1-53eaf6e
* 2019.04.24-NB-1f2071e

I think it's working fine.

BTW: Fdroid repositories are not meant to be accessed using a browser.

**Comment by Lineflyer** [comment]
I don't see 2019.04.24-NB others I do see.

**Comment by kumy** [comment]
Did you refreshed the repo? They are present in the index file https://fdroid.cgeo.org/nightly/index.xml

**Comment by Lineflyer** [comment]
I triggered the publish job manually, now todays nightly is available as well.

**Comment by kumy** [comment]
strange as I've updated my installed version today at ~12h30… 👽

**Comment by Lineflyer** [comment]
mmh...maybe my fdroid did not update the packet source from the server for some reason.

I will monitor it next days by loading my nightlies via fdroid.

**Comment by rsudev** [comment]
The user reported, that after removing and re-adding the feed it started working again, therefore closing  here.
