### ISSUE TITLE
Nightly not updated since 2023.04.16-NB-ba0042c

### ISSUE THREAD

**Issue by Lomanic** [cgeo/cgeo-fdroid#9]
Last version reported in f-droid for the https://fdroid.cgeo.org/nightly repository is `2023.04.16-NB-ba0042c`.

Disabling then re-enabling the repo, or deleting then re-adding the repo (like in https://github.com/cgeo/cgeo-fdroid/issues/8#issuecomment-494544153) didn't fix this issue.

To exclude an issue [with my F-Droid client](https://f-droid.org/fr/packages/org.fdroid.fdroid/), I even [installed a brand new client](https://f-droid.org/fr/packages/com.looker.droidify/), added the nightly repository, and the last version for cgeo was also reported as `2023.04.16-NB-ba0042c` in this client.

Can anyone else confirm this?

**Comment by john-magnus** [comment]
Can confirm. 

2023.04.16 was the last update.

F-droid version 1.16.3

(Sorry. Missed this and created a separate issue.)

**Comment by Lineflyer** [comment]
The reason is, that our designated Jenkins executor for F-Droid is offline.
Cause is, that @kumy has a change in the IP address which needs to be added to the CI firewall whitelist by @mucek4.

@mucek4 
You received a mail with details from @kumy last days. Can you adapt the configuration accordingly, so that our F-Droid executor comes up again?

**Comment by kumy** [comment]
Thanks to @mucek4 the firewall is now accepting the executor again. [Pending job](https://ci.cgeo.org/view/FDroid/job/Publish%20FDroid%20-%20NIGHTLY/) ran successfully.

**Comment by john-magnus** [comment]
c:geo's nightly repository is working again with f-droid.

Latest build available is from the 16th of may.

**Comment by Lineflyer** [comment]
Thanks for the feedback. Closing then.

**Comment by john-magnus** [comment]
The issue with missing nightlies in F-droid  have creeped back.

**Comment by kumy** [comment]
I'll check ASAP

**Comment by kumy** [comment]
@mucek4 the firewall doesn't let me in, could you please check on your side?
![image](https://github.com/cgeo/cgeo-fdroid/assets/176794/160227a0-4e8a-47ad-8bf5-a27b0c5d5658)

**Comment by kumy** [comment]
It's working again :partying_face: https://ci.cgeo.org/job/Publish%20FDroid%20-%20NIGHTLY/2724/
Nothing changed on my side...

![image](https://github.com/cgeo/cgeo-fdroid/assets/176794/b3f9ea10-6929-4365-8c34-d90a04642a44)

**Comment by john-magnus** [comment]
Sorry to keep bringing this back to life. Again, no idea if it's the same issue. But nightlies are not updating via f-droid. After the 16th there was one single update for the 24th. Then it stopped again..

**Comment by john-magnus** [comment]
![Screenshot_20230530-231059](https://github.com/cgeo/cgeo-fdroid/assets/1545102/3c7f6de6-3be5-4acf-9202-896e62c3cba2)

**Comment by kumy** [comment]
Thanks @john-magnus for reporting! It should be fixed now. It was a problem on my side, an old VPN configuration was still present which modified the network `route`s.
